# Generated by Django 3.1 on 2020-10-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201017_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.businessowner'),
            preserve_default=False,
        ),
    ]
